assets:
  port_offset: 1
  rails_root: "server"
factotum:
  port_offset: 3
kiosk:
  port_offset: 4
api:
  port_offset: 5
ejournal_locator:
  port_offset: 6
biographies:
  port_offset: 9
architecture_drawings:
  port_offset: 10
reserves:
  port_offset: 11
tedx:
  port_offset: 12
siphon:
  port_offset: 13
  rails_root: "server"
hesburgh_api:
  port_offset: 14
  rails_root: "server"
fresh_writing:
  port_offset: 15
discover:
  port_offset: 16
honeycomb:
  port_offset: 17
beehive:
  port_offset: 18
honeypot:
  port_offset: 19
zucchetto:
  port_offset: 20
annex_ims:
  port_offset: 21
mobile:
  port_offset: 22
buzz:
  port_offset: 23
siphon:
  port_offset: 24